#!/bin/bash

if [ "$#" -eq 1 ] ; then
	if [ $1 == "--clean" ] ; then
		make clean
	else
		echo "The argument $1 is not a known argument"
	fi
elif [ "$#" -gt 1 ] ; then
	echo "Unaccepted number of aruments"
else
	./configure
	make
fi
